# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 00:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coinlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nick', models.CharField(max_length=10)),
                ('ammount', models.IntegerField()),
                ('worth', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=24)),
                ('roi', models.IntegerField()),
                ('logo', models.CharField(max_length=500)),
                ('nodecount', models.IntegerField()),
                ('coinslocked', models.IntegerField()),
                ('sharetime', models.TimeField()),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=24)),
                ('mcap', models.CharField(max_length=255)),
                ('weekcoins', models.DecimalField(decimal_places=5, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
