# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlist',
            name='active',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
