# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171019_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinlist',
            name='logo',
            field=models.CharField(max_length=500, verbose_name='Imagem da Moeda'),
        ),
    ]
