# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171019_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodesconf', models.CharField(max_length=855, verbose_name='node.conf')),
                ('bootstrap', models.CharField(max_length=855, verbose_name='blockchain')),
                ('nodecount', models.IntegerField(verbose_name='Quantidade de Nodes')),
                ('coinslocked', models.IntegerField(verbose_name='Moedas Travadas')),
                ('sharetime', models.TimeField(verbose_name='Tempo entre Shares')),
                ('mcap', models.CharField(max_length=255, verbose_name='Link do Marketcap')),
            ],
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='coinslocked',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='mcap',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='nodecount',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='sharetime',
        ),
        migrations.AddField(
            model_name='details',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coinlist'),
        ),
    ]
