# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171019_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinlist',
            name='active',
        ),
        migrations.AddField(
            model_name='coinlist',
            name='exchange',
            field=models.CharField(choices=[('1', 'Bittrex'), ('2', 'Cryptopia'), ('3', 'Novaexchange'), ('4', 'Yobit'), ('5', 'CCex')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
